text_transaction = {
    'user_error_message': {
        'en': 'sorry, somthing went wrong!',
        'fa': 'ببخشید، مشکلی وجود داشت!'
    },
    'start_menu': {
        'en': 'Hi, welcome to DataGuardian Bot.',
        'fa': 'درود، به ربات دیتاگاردین خوش آمدید!'
    },
    'select_section': {
        'en': 'Select the section you want:',
        'fa': 'بخش مورد نظر را انتخاب کنید:'
    },
    'select_address': {
        'en': 'Select the address:',
        'fa': 'آدرس مود نظر را انتخاب کنید:'
    },
    'add_address_conversation': {
        'en': 'Please Send IP or Domain address.',
        'fa': 'لطفا آدرس آیپی یا دامنه را بفرستید'
    },
    'there_is_no_address': {
        'en': 'you have not register any address.\nAdd new address with below button',
        'fa': 'شما آدرسی ثبت نکردید!\nبا گزینه زیر یک آدرس جدید ثبت کنید'
    },
    'there_is_no_country': {
        'en': 'There is no country!',
        'fa': 'کشوری وجود ندارد!'
    },
    'cancel_message': {
        'en': 'Conversation Canceled!',
        'fa': 'کانورسیشن بسته شد!'
    },
    'waiting_for_check_address': {
        'en': 'Wait a few second ⏳\nChecking Address ...',
        'fa': 'چندثانیه صبر کنید ⏳\nدرحال بررسی آدرس ...'
    },
    'address_in_block_list': {
        'en': 'You can not add this address right now\nplease Try again later',
        'fa': 'درحال حاضر نمیتوانید این آدرس را اضافه کنید!\nلطفا بعدا تلاش کنید.'
    },
    'address_score_not_enough': {
        'en': 'Address score not enough To register in BOT!\nIf you believe this is a mistake, please call support.',
        'fa': 'آدرس امتیاز کافی برای ثبت شدن داخل ربات را دریافت نکرد!\nاگر فکر میکنید این یک اشتباه است، لطفا با پشتیبانی در ارتباط باشید.'
    },
    'address_register_successfull': {
        'en': 'Address register in BOT successfull✅',
        'fa': 'آدرس با موفقیت در ربات ثبت شد✅'
    },
    'address_is_not_unique': {
        'en': 'You have already register this address and you can not register it again❌',
        'fa': 'شما قبلا این آدرس را اضافه کردید و نمیتوانید دوباره این کار را انجام دهید❌'
    },
    'select_country': {
        'en': 'Select the countries where you will be notified when the IP is restricted in that.',
        'fa': 'کشورهایی را انتخاب کنید که با محدود شدن آیپی در آن ها، نوتیفیکشن دریافت کنید.'
    },
    'operation_successfull': {
        'en': 'The operation successful✅',
        'fa': 'عملیات با موفقیت انجام شد✅'
    },
    'somthing_wrong_in_address': {
        'en': 'The operation not successful❌\nThere may have been a problem in address, re-register the address or contact support!',
        'fa': 'عملیات موفقیت آمیز نبود!❌\nاحتمالا مشکلی در آدرس وجود دارد، آدرس را دوباره ثبت کنید یا با پشتیبانی تماس بگیرید'
    },
}

keyboard_transaction = {
    'main_menu_ip_guardian': {
        'en': 'IP Guardian',
        'fa': 'آیپی گاردین'
    },
    'main_menu_virtualizor': {
        'en': 'Virtualizor Manager',
        'fa': 'مدیریت Virtualizor'
    },
    'setting': {
        'en': 'Setting ⚙️',
        'fa': 'تنظیمات ⚙️'
    },
    'back_button': {
        'en': 'Back ↰',
        'fa': 'برگشت ↰'
    },
    'add_ip': {
        'en': 'Add IP ➕',
        'fa': 'اضافه کردن آیپی ➕'
    },
    'view_ips': {
        'en': 'My IPs',
        'fa': 'آیپی های من'
    },
    'help_button': {
        'en': 'Help 📚',
        'fa': 'راهنما 📚'
    },
    'cancel_button': {
        'en': 'Cancel ✘',
        'fa': 'انصراف ✘'
    },
    'ip_guardian_setting': {
        'en': 'IpGuadian Settings',
        'fa': 'تنظیمات آیپی گاردین'
    }
}

countries_and_flags = {
    "Afghanistan": "🇦🇫",
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "Andorra": "🇦🇩",
    "Angola": "🇦🇴",
    "Antigua and Barbuda": "🇦🇬",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahamas": "🇧🇸",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Barbados": "🇧🇧",
    "Belarus": "🇧🇾",
    "Belgium": "🇧🇪",
    "Belize": "🇧🇿",
    "Benin": "🇧🇯",
    "Bhutan": "🇧🇹",
    "Bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Botswana": "🇧🇼",
    "Brazil": "🇧🇷",
    "Brunei": "🇧🇳",
    "Bulgaria": "🇧🇬",
    "Burkina Faso": "🇧🇫",
    "Burundi": "🇧🇮",
    "Cabo Verde": "🇨🇻",
    "Cambodia": "🇰🇭",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Central African Republic": "🇨🇫",
    "Chad": "🇹🇩",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Hong Kong": "🇨🇳",
    "Colombia": "🇨🇴",
    "Comoros": "🇰🇲",
    "Congo, Democratic Republic of the": "🇨🇩",
    "Congo, Republic of the": "🇨🇬",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Cuba": "🇨🇺",
    "Cyprus": "🇨🇾",
    "Czechia": "🇨🇿",
    "Denmark": "🇩🇰",
    "Djibouti": "🇩🇯",
    "Dominica": "🇩🇲",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "Equatorial Guinea": "🇬🇶",
    "Eritrea": "🇪🇷",
    "Estonia": "🇪🇪",
    "Eswatini": "🇸🇿",
    "Ethiopia": "🇪🇹",
    "Fiji": "🇫🇯",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "Gabon": "🇬🇦",
    "Gambia": "🇬🇲",
    "Georgia": "🇬🇪",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Greece": "🇬🇷",
    "Grenada": "🇬🇩",
    "Guatemala": "🇬🇹",
    "Guinea": "🇬🇳",
    "Guinea-Bissau": "🇬🇼",
    "Guyana": "🇬🇾",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "Hungary": "🇭🇺",
    "Iceland": "🇮🇸",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ireland": "🇮🇪",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Kazakhstan": "🇰🇿",
    "Kenya": "🇰🇪",
    "Kiribati": "🇰🇮",
    "Korea, North": "🇰🇵",
    "Korea, South": "🇰🇷",
    "Kuwait": "🇰🇼",
    "Kyrgyzstan": "🇰🇬",
    "Laos": "🇱🇦",
    "Latvia": "🇱🇻",
    "Lebanon": "🇱🇧",
    "Lesotho": "🇱🇸",
    "Liberia": "🇱🇷",
    "Libya": "🇱🇾",
    "Liechtenstein": "🇱🇮",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Madagascar": "🇲🇬",
    "Malawi": "🇲🇼",
    "Malaysia": "🇲🇾",
    "Maldives": "🇲🇻",
    "Mali": "🇲🇱",
    "Malta": "🇲🇹",
    "Marshall Islands": "🇲🇭",
    "Mauritania": "🇲🇷",
    "Mauritius": "🇲🇺",
    "Mexico": "🇲🇽",
    "Micronesia": "🇫🇲",
    "Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Mongolia": "🇲🇳",
    "Montenegro": "🇲🇪",
    "Morocco": "🇲🇦",
    "Mozambique": "🇲🇿",
    "Myanmar": "🇲🇲",
    "Namibia": "🇳🇦",
    "Nauru": "🇳🇷",
    "Nepal": "🇳🇵",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Nicaragua": "🇳🇮",
    "Niger": "🇳🇪",
    "Nigeria": "🇳🇬",
    "North Macedonia": "🇲🇰",
    "Norway": "🇳🇴",
    "Oman": "🇴🇲",
    "Pakistan": "🇵🇰",
    "Palau": "🇵🇼",
    "Palestine": "🇵🇸",
    "Panama": "🇵🇦",
    "Papua New Guinea": "🇵🇬",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Philippines": "🇵🇭",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Rwanda": "🇷🇼",
    "Saint Kitts and Nevis": "🇰🇳",
    "Saint Lucia": "🇱🇨",
    "Saint Vincent and the Grenadines": "🇻🇨",
    "Samoa": "🇼🇸",
    "San Marino": "🇸🇲",
    "Sao Tome and Principe": "🇸🇹",
    "Saudi Arabia": "🇸🇦",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Seychelles": "🇸🇨",
    "Sierra Leone": "🇸🇱",
    "Singapore": "🇸🇬",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Solomon Islands": "🇸🇧",
    "Somalia": "🇸🇴",
    "South Africa": "🇿🇦",
    "South Sudan": "🇸🇸",
    "Spain": "🇪🇸",
    "Sri Lanka": "🇱🇰",
    "Sudan": "🇸🇩",
    "Suriname": "🇸🇷",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Syria": "🇸🇾",
    "Taiwan": "🇹🇼",
    "Tajikistan": "🇹🇯",
    "Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Timor-Leste": "🇹🇱",
    "Togo": "🇹🇬",
    "Tonga": "🇹🇴",
    "Trinidad and Tobago": "🇹🇹",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "Turkmenistan": "🇹🇲",
    "Tuvalu": "🇹🇻",
    "Uganda": "🇺🇬",
    "Ukraine": "🇺🇦",
    "UAE": "🇦🇪",
    "United Arab Emirates": "🇦🇪",
    "UK": "🇬🇧",
    "United Kingdom": "🇬🇧",
    "USA": "🇺🇸",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Vanuatu": "🇻🇺",
    "Vatican City": "🇻🇦",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼"
}